name: Robotics Club
title: Robotics Club
url: https://roboticsclubiitk.github.io
paginate: 5
paginate_path: "/blog/page:num/"
plugins: 
- jekyll-paginate

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false

highlighter: rouge

exclude: ["/docs", vendor]
destination: "docs/"
